/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package user.registration.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRegistration service. Represents a row in the &quot;UserRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>user.registration.service.model.impl.UserRegistrationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>user.registration.service.model.impl.UserRegistrationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistration
 * @generated
 */
@ProviderType
public interface UserRegistrationModel
	extends BaseModel<UserRegistration>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user registration model instance should use the {@link UserRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this user registration.
	 *
	 * @return the primary key of this user registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user registration.
	 *
	 * @param primaryKey the primary key of this user registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user registration.
	 *
	 * @return the uuid of this user registration
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user registration.
	 *
	 * @param uuid the uuid of this user registration
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the user registration ID of this user registration.
	 *
	 * @return the user registration ID of this user registration
	 */
	public long getUserRegistrationId();

	/**
	 * Sets the user registration ID of this user registration.
	 *
	 * @param userRegistrationId the user registration ID of this user registration
	 */
	public void setUserRegistrationId(long userRegistrationId);

	/**
	 * Returns the name of this user registration.
	 *
	 * @return the name of this user registration
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user registration.
	 *
	 * @param name the name of this user registration
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this user registration.
	 *
	 * @return the surname of this user registration
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this user registration.
	 *
	 * @param surname the surname of this user registration
	 */
	public void setSurname(String surname);

	/**
	 * Returns the birthdate of this user registration.
	 *
	 * @return the birthdate of this user registration
	 */
	public Date getBirthdate();

	/**
	 * Sets the birthdate of this user registration.
	 *
	 * @param birthdate the birthdate of this user registration
	 */
	public void setBirthdate(Date birthdate);

	/**
	 * Returns the email of this user registration.
	 *
	 * @return the email of this user registration
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user registration.
	 *
	 * @param email the email of this user registration
	 */
	public void setEmail(String email);

	/**
	 * Returns the group ID of this user registration.
	 *
	 * @return the group ID of this user registration
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user registration.
	 *
	 * @param groupId the group ID of this user registration
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user registration.
	 *
	 * @return the company ID of this user registration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user registration.
	 *
	 * @param companyId the company ID of this user registration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user registration.
	 *
	 * @return the user ID of this user registration
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user registration.
	 *
	 * @param userId the user ID of this user registration
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user registration.
	 *
	 * @return the user uuid of this user registration
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user registration.
	 *
	 * @param userUuid the user uuid of this user registration
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user registration.
	 *
	 * @return the user name of this user registration
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user registration.
	 *
	 * @param userName the user name of this user registration
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user registration.
	 *
	 * @return the create date of this user registration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user registration.
	 *
	 * @param createDate the create date of this user registration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user registration.
	 *
	 * @return the modified date of this user registration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user registration.
	 *
	 * @param modifiedDate the modified date of this user registration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this user registration.
	 *
	 * @return the field1 of this user registration
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this user registration.
	 *
	 * @param field1 the field1 of this user registration
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this user registration.
	 *
	 * @return the field2 of this user registration
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this user registration is field2.
	 *
	 * @return <code>true</code> if this user registration is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this user registration is field2.
	 *
	 * @param field2 the field2 of this user registration
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this user registration.
	 *
	 * @return the field3 of this user registration
	 */
	public int getField3();

	/**
	 * Sets the field3 of this user registration.
	 *
	 * @param field3 the field3 of this user registration
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this user registration.
	 *
	 * @return the field4 of this user registration
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this user registration.
	 *
	 * @param field4 the field4 of this user registration
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this user registration.
	 *
	 * @return the field5 of this user registration
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this user registration.
	 *
	 * @param field5 the field5 of this user registration
	 */
	public void setField5(String field5);

}